import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { buildSite } from '../src/site-builder.js';

test('builds a complete blog from markdown folders', async () => {
  const temporary = await mkdtemp(path.join(tmpdir(), 'markdown-blog-test-'));
  const source = path.join(temporary, 'content');
  const output = path.join(temporary, '_site');
  await mkdir(path.join(source, 'llm'), { recursive: true });
  await writeFile(path.join(source, 'llm', 'attention.md'), '# Attention\n\n## Formula\n\n$E=mc^2$\n\n![diagram](/img/diagram.png)');
  await writeFile(path.join(source, 'llm', 'index.md'), '---\ntitle: 大语言模型列表\nsubtitle: 模型与推理\narticle-list:\n  - article-title: Attention from index\n    article-url: /llm/attention\n    article-date: 2026-09-30\n    article-desc: This complete description comes from index.md.\n    article-tags: [Transformer, Attention]\n---');
  await writeFile(path.join(source, '_config.yaml'), 'title: Config Blog\nauthor: Config Author\nposts_per_page: 1\ncategories:\n  llm: 大语言模型\n');
  await writeFile(path.join(source, 'custom.html'), '<h1>Custom page</h1>');
  try {
    const result = await buildSite({ source, output, title: 'Test Blog', baseUrl: '/docs/', cname: 'example.com' });
    assert.deepEqual({ posts: result.posts, categories: result.categories }, { posts: 1, categories: 1 });
    const home = await readFile(path.join(output, 'index.html'), 'utf8');
    const categoryPage = await readFile(path.join(output, 'llm/index.html'), 'utf8');
    const article = await readFile(path.join(output, 'llm/attention/index.html'), 'utf8');
    const legacyArticle = await readFile(path.join(output, 'llm/attention.html'), 'utf8');
    assert.match(home, /Test Blog/);
    assert.match(home, /大语言模型/);
    assert.match(categoryPage, /大语言模型/);
    assert.doesNotMatch(home, /href="\/docs\/llm\/attention\/"/);
    assert.match(categoryPage, /href="\/docs\/llm\/attention\/"/);
    assert.match(categoryPage, /Attention from index/);
    assert.match(categoryPage, /This complete description comes from index\.md\./);
    assert.match(categoryPage, /class="article-date">2026-09-30<\/time>/);
    assert.match(categoryPage, /class="article-tags"><span class="article-tag">Transformer<\/span><span class="article-tag">Attention<\/span>/);
    assert.doesNotMatch(categoryPage, /<span>大语言模型<\/span>/);
    assert.doesNotMatch(categoryPage, /class="post-meta">大语言模型/);
    assert.match(categoryPage, /class="pagination" data-pagination data-list="article-list-llm" data-per-page="1"/);
    assert.match(home, /LEARNING BY DOING/);
    assert.doesNotMatch(home, /最近文章/);
    assert.doesNotMatch(home, /class="category-card"/);
    assert.match(home, /class="code-rain"/);
    assert.match(home, /Blog compiled successfully/);
    assert.match(home, /class="lucide /);
    assert.match(home, /class="desktop-nav"/);
    assert.match(home, /assets\/blog\.css\?v=[a-f0-9]{10}/);
    assert.match(article, /<aside class="article-toc">/);
    assert.match(article, /<mjx-container/);
    assert.match(article, /src="\/docs\/img\/diagram\.png"/);
    assert.match(article, /<h1 id="attention">Attention<\/h1><p class="article-views">本页总阅读量 <b id="busuanzi_page_pv">加载中\.\.\.<\/b> 次<\/p>/);
    assert.match(article, /本站总访问量 <b id="busuanzi_site_pv">加载中\.\.\.<\/b> 次/);
    assert.match(article, /cdn\.busuanzi\.cc\/busuanzi\/3\.6\.9\/busuanzi\.min\.js/);
    assert.equal(legacyArticle, article);
    assert.equal(await readFile(path.join(output, 'custom.html'), 'utf8'), '<h1>Custom page</h1>');
    assert.match(await readFile(path.join(output, 'assets/blog.js'), 'utf8'), /下一页/);
    const styles = await readFile(path.join(output, 'assets/blog.css'), 'utf8');
    assert.match(styles, /body\{min-height:100vh;display:flex;flex-direction:column\}/);
    assert.match(styles, /footer\{width:100%;margin-top:auto/);
    assert.equal(await readFile(path.join(output, 'CNAME'), 'utf8'), 'example.com\n');
  } finally {
    await rm(temporary, { recursive: true, force: true });
  }
});
